### ISSUE TITLE
(ios) can't control media after session is returned after app restart

### ISSUE THREAD

**Issue by Lindsay-Needs-Sleep** [miloproductionsinc/cordova-plugin-chromecast#6]
Originally found by @JumBay [here](https://github.com/miloproductionsinc/cordova-plugin-chromecast/issues/5#issuecomment-575894480)

> I did find another similar issue.
> Cast something, kill the app, reopen it. The session will be retrieved, the media will be retrieved as well with the right playerState but you cannot interact with the media object anymore, play, pause... methods have no effect.

May be a bug on Android as well.

**Comment by Lindsay-Needs-Sleep** [comment]
@JumBay I believe this issue is fixed now.  
Thanks for the report again!
Please let me know if you find any other bugs!

**Comment by JumBay** [comment]
@Lindsay-Needs-Sleep Thanks to taking care of. 
It seems working, but not all the time. I got an error sometimes on the first play and I don't receive any events even if the video plays on the chromecast: 
```
Unhandled Promise rejection: – "undefined is not an object (evaluating 'this._getMedia().mediaSessionId = 'invalidated'')" – "; Zone:" – "<root>" – "; Task:" – "Promise.then" – "; Value:" (2)
TypeError: undefined is not an object (evaluating 'this._getMedia().mediaSessionId = 'invalidated'') — chrome.cast.js:893
"http://localhost:8100/plugins/cordova-plugin-chromecast/www/chrome.cast.js:893:21
http://localhost:8100/plugins/cordova-plugin-chromecast/www/chrome.cast.js:731:31
http://localhost:8100/plugins/cordova-plugin-chromecast/www/chrome.cast.js:1476:65
callbackFromNative@http://localhost:8100/cordova.js:295:63
http://localhost:8100/plugins/cordova-plugin-ionic-webview/src/www/ios/ios-wkwebview-exec.js:129:35
```

**Comment by JumBay** [comment]
If I wrap this with a try catch block I don't have the error anymore obviously, but on the restart, the issue is still present

**Comment by Lindsay-Needs-Sleep** [comment]
Oh, yep, that error makes sense.  I'll fix it.
Not sure why I never saw that error though. :/

---------------------------------------------
Could you make a new issue for this?

(In the new issue) Can you expand on this a bit too please?
> and I don't receive any events even if the video plays on the chromecast:

So this is a problem even when you don't receive the error?

Is the following correct?
* Start the app (no chromecast session)
* start session
* `loadMedia`
* Maybe you get the above error, maybe not
* Either way, you don't receive any `media.addUpdateListener` events?
Can you include this info in the new issue as well?

Thanks so much!  (Sorry I am getting busy with some other things, so if I know exactly what to do to reproduce it I should be able to fix it sooner.)

**Comment by JumBay** [comment]
Sorry, I wasn't clear enough for this part, I said I don't receive any event because of the error. After I've wrapped it with the try-catch block, it works as before. But it seems that on app restart, the callback`sessionListener`  of  `chrome.cast.ApiConfig` doesn't always have a working `media` object. If I do add a timeout like this it works with no issue: 
```js 
new chrome.cast.ApiConfig(new chrome.cast.SessionRequest(chrome.cast.media.DEFAULT_MEDIA_RECEIVER_APP_ID), function (session) {
            // The session listener is only called under the following conditions:
            // * will be called shortly chrome.cast.initialize is run
            // * if the device is already connected to a cast session
            // Basically, this is what allows you to re-use the same cast session
            // across different pages and after app restarts
          setTimeout(()=>{

            _this.onExistingSessionJoined(session);
          }, 5000); // High delay on purpose :)
        }
...
```
